on:
  push:
    branches:
      - master
jobs:
  build_docs_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Dependencies
      run: |
        echo `python3 --version`
        sudo apt-get install -y python-setuptools
        python3 -m pip install --upgrade pip
        python3 -m pip install -U sphinx
        python3 -m pip install setuptools
        python3 -m pip install torch
        git clone https://github.com/pytorch/pytorch_sphinx_theme
        python3 -m pip install -e pytorch_sphinx_theme
        python3 -m pip install recommonmark
        python3 -m pip install katex
        python3 -m pip install sphinxcontrib.katex
        python3 -m pip install sphinx_markdown_tables
        python3 -m pip install torchserve torch-model-archiver torch-workflow-archiver
    - name: Build the docset
      run: cd ./docs/sphinx ; export PATH=$PATH:$(python3 -m site --user-base)/bin/ ; make html
      id: build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs/sphinx/build/html
          CLEAN_EXCLUDE: '["_config.yml"]'
    - name: Open issue on failure
      if: ${{ failure() && github.event_name  == 'schedule' }}
      uses: rishabhgupta/git-action-issue@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: Doc automation failed
        body:  Commit ${{ github.sha }} daily scheduled [CI run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) failed, please check why
        assignees: ''